"use client";
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "../components/nav-bar";
import { Providers } from "../components/providers";
import { ClientOnly } from "@chakra-ui/react";

// TODO: Uncomment when using server components

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// TODO: Add metadata for the page when reverted to server component
// export const metadata: Metadata = {
//   title: "Welcome to my Blog",
//   description: "Generated by create-nx-workspace",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        // className={`${geistSans.variable} ${geistMono.variable}`}
        suppressHydrationWarning
      >
        <Providers>
          <ClientOnly>
            <NavBar />
            {children}
          </ClientOnly>
        </Providers>
      </body>
    </html>
  );
}
